// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtlpry-ETyzQ0CKm7MeVRue2nmi2zruEw',
    appId: '1:782529105765:web:33871e703ed79580735b8c',
    messagingSenderId: '782529105765',
    projectId: 'we-chat-da0fc',
    authDomain: 'we-chat-da0fc.firebaseapp.com',
    storageBucket: 'we-chat-da0fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjMsPPb5UGT56-egx_LoiWO_uDHtqdM4',
    appId: '1:782529105765:android:b00cd5f75fc11f2b735b8c',
    messagingSenderId: '782529105765',
    projectId: 'we-chat-da0fc',
    storageBucket: 'we-chat-da0fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7iq-a1WLMgHvFcnM1mNna25Du84Yy5A',
    appId: '1:782529105765:ios:66ffe2396aa29e65735b8c',
    messagingSenderId: '782529105765',
    projectId: 'we-chat-da0fc',
    storageBucket: 'we-chat-da0fc.appspot.com',
    androidClientId: '782529105765-flcu5e1aoq4pqk9nk4leomeijk5uq2am.apps.googleusercontent.com',
    iosClientId: '782529105765-aakqnir0v762c96jvt4p50ntgnievlbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7iq-a1WLMgHvFcnM1mNna25Du84Yy5A',
    appId: '1:782529105765:ios:66ffe2396aa29e65735b8c',
    messagingSenderId: '782529105765',
    projectId: 'we-chat-da0fc',
    storageBucket: 'we-chat-da0fc.appspot.com',
    androidClientId: '782529105765-flcu5e1aoq4pqk9nk4leomeijk5uq2am.apps.googleusercontent.com',
    iosClientId: '782529105765-aakqnir0v762c96jvt4p50ntgnievlbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtlpry-ETyzQ0CKm7MeVRue2nmi2zruEw',
    appId: '1:782529105765:web:c3475c748a5cad62735b8c',
    messagingSenderId: '782529105765',
    projectId: 'we-chat-da0fc',
    authDomain: 'we-chat-da0fc.firebaseapp.com',
    storageBucket: 'we-chat-da0fc.appspot.com',
  );

}